/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CreateCustomTrackRouteImport } from './routes/create-custom-track'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChooseSongRouteImport } from './routes/choose-song'
import { Route as IndexRouteImport } from './routes/index'

const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCustomTrackRoute = CreateCustomTrackRouteImport.update({
  id: '/create-custom-track',
  path: '/create-custom-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChooseSongRoute = ChooseSongRouteImport.update({
  id: '/choose-song',
  path: '/choose-song',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/choose-song': typeof ChooseSongRoute
  '/contact': typeof ContactRoute
  '/create-custom-track': typeof CreateCustomTrackRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/choose-song': typeof ChooseSongRoute
  '/contact': typeof ContactRoute
  '/create-custom-track': typeof CreateCustomTrackRoute
  '/legal': typeof LegalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/choose-song': typeof ChooseSongRoute
  '/contact': typeof ContactRoute
  '/create-custom-track': typeof CreateCustomTrackRoute
  '/legal': typeof LegalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/choose-song'
    | '/contact'
    | '/create-custom-track'
    | '/legal'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/choose-song' | '/contact' | '/create-custom-track' | '/legal'
  id:
    | '__root__'
    | '/'
    | '/choose-song'
    | '/contact'
    | '/create-custom-track'
    | '/legal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChooseSongRoute: typeof ChooseSongRoute
  ContactRoute: typeof ContactRoute
  CreateCustomTrackRoute: typeof CreateCustomTrackRoute
  LegalRoute: typeof LegalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-custom-track': {
      id: '/create-custom-track'
      path: '/create-custom-track'
      fullPath: '/create-custom-track'
      preLoaderRoute: typeof CreateCustomTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choose-song': {
      id: '/choose-song'
      path: '/choose-song'
      fullPath: '/choose-song'
      preLoaderRoute: typeof ChooseSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChooseSongRoute: ChooseSongRoute,
  ContactRoute: ContactRoute,
  CreateCustomTrackRoute: CreateCustomTrackRoute,
  LegalRoute: LegalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
